In [1]:
"""import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables."""

'import numpy as np\nlist_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]\narray_list = np.array(object = list_)\nQ1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code\nto print the data types of both the variables.'

In [3]:
import numpy as np
list=['1','2','3','4','5']
array_list=np.array(list)
print(type(list))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
"""Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list."""

'Q2. Write a code to print the data type of each and every element of both the variables list_ and\narra_list.'

In [10]:
import numpy as np
list=['1','2','3','4','5']
array_list=np.array(list)
print("Data type of list")
for i in list:
    print(type(i))

    
    
print("Data type of arry_list")
for i in array_list:
    print(type(i))

Data type of list
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of arry_list
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [8]:
"""Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)"""

'Q3. Considering the following changes in the variable, array_list:\narray_list = np.array(object = list_, dtype = int)\nWill there be any difference in the data type of the elements present in both the variables, list_ and\narra_list? If so then print the data types of each and every element present in both the variables, list_\nand arra_list.\nConsider the below code to answer further questions:\nimport numpy as np\nnum_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]\nnum_array = np.array(object = num_list)'

In [11]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print("Data type of num_list")
for i in num_list:
    print(type(i))
    
print("Data type of num_array")
for i in num_array:
    print(type(i))

Data type of num_list
<class 'list'>
<class 'list'>
Data type of num_array
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
"""Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size"""

'Q4. Write a code to find the following characteristics of variable, num_array:\n(i) shape\n(ii) size'

In [15]:
import numpy as np
l=[1,2,3,4,5]
l1=np.array(l)

In [16]:
l1

array([1, 2, 3, 4, 5])

In [18]:
np.shape(l1)

(5,)

In [19]:
np.size(l1)

5

In [20]:
"""Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]"""

'Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array\ncreation function.\n[Hint: The size of the array will be 9 and the shape will be (3,3).]'

In [36]:
import numpy as np
create_zeros=np.zeros((3,3))
print(create_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
"""Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]"""

'Q6. Create an identity matrix of shape (5,5) using numpy functions?\n[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]'

In [40]:
import numpy as np
identity_matrix=np.eye((5,5))
print(identity_matrix)

TypeError: 'tuple' object cannot be interpreted as an integer